services:
  - type: web
    name: stephs-english-lab-bot
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        sync: false
      - key: CHANNEL_SECRET
        sync: false
